project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary of CASA0023 Remotely Sensing Cities and Environments 23/24"
  author: "Jiaming Li"
  date: "1/20/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Week_2.qmd
    - Week_3.qmd
    - Week_4.qmd
    - GEE.qmd
    - Classification_I.qmd
    - Classification_II.qmd
    - SAR.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

